# Site settings
title: Welcome to Quin Kennedy
email: quinkennedy@gmail.com
description: "Portfolio website for Quin Kennedy."
baseurl: "http://quinkennedy.github.io"
url: "http://quinkennedy.com"
username: "quinkennedy"

# Build settings
markdown: kramdown
permalink: pretty
